apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  creationTimestamp: "2020-12-20T23:30:34Z"
  finalizers:
  - gke.networking.io/l4-ilb-v1
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.34.2
    component: controller
    heritage: Helm
    release: nginx-ingress
  name: nginx-ingress-controller
  namespace: nginx-ingress
  resourceVersion: "206696"
  selfLink: /api/v1/namespaces/nginx-ingress/services/nginx-ingress-controller
  uid: 7bda8a95-c6c4-464f-a1c2-a29f0ec3fce3
spec:
  clusterIP: 10.65.5.208
  externalTrafficPolicy: Local
  healthCheckNodePort: 30849
  ports:
  - name: http
    nodePort: 31728
    port: 80
    protocol: TCP
    targetPort: https
  - name: https
    nodePort: 32215
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
    app.kubernetes.io/component: controller
    release: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.128.0.18
